FROM arm32v6/python:3.6-alpine3.8

VOLUME /config

ENV TZ="Europe/Paris"
ENV OPTS=""

COPY . /
RUN python setup.py develop

WORKDIR /
ENTRYPOINT ["python", "/usr/local/bin/enoceanmqtt", "/config/enoceanmqtt.conf", "${OPTS}"]
